### PR TITLE
Translated into Russian.

### PR DESCRIPTION
**Pull request by eklipse2009**
This is a translation of all messages into Russian.
Please consider adding it into the project.
P. S. I'm a native speaker.

### CODE REVIEW

**Comment by panique** [comment]
Sorry, but this project is closed. Please have a look on the readme, there are two links to two forks that are still developed! 

Have a great time

**Comment by eklipse2009** [comment]
Your new project sucks.
I will be using this version because it is the best of the 4.
WAS IT THAT HARD TO PRESS A BUTTON AND MY TRANSLATION WOULD BE AUTOMATICALLY ADDED FOR FUTURE USE BY OTHER DEVELOPERS???
I've never seen such arrogancy before.

**Comment by panique** [comment]
@eklipse2009 

First, seriously, go fuck yourself, you don't have the right to talk like that here. This is a totally free project I'm doing in my rare freetime, and I simply don't have the time to do it anymore because I have a job and have to feed some mouths. Be thankful for the code and all the work others have done for you, stupid, and read the according information before you judge.

As explained 100x times before (have you even read the readme ?), please NEVER commit to master branch, always to develop branch, otherwise it's not possible to merge the commit correctly (and it would take a long time to unfiddle this mess). Also, as discussed and explained 100x before, this project is NOT DEVELOPED ANYMORE, and adding a translation takes a lot of testing, plus you'll have to find a trustable native speaker every time you change a little bit of text somewhere. I have done this lot of times before and it was so much stress and a time-killer.
Third, as clearly explained and impossible to miss, there are two forks of this projects from some awesome people who still maintain these forks, if it's really important for you to add a russian translation, then your commit to these projects.

I've simply written a nice and helpful comment, showing you the forks that you need, and everything that comes back is pure arrogance, and then you call me arrogant. This is why the internet is such a bad place sometimes. I hope karma will judge you.

Also: There's absoutly no reason to say "your new project sucks" (out of curiosity, what exactly "sucks" for you), but this clearly describes your intellect very well. The "new project" is just a cleaner, well-maintained version of this one here, so ... aahh, what am I even talking to you.

P.S. Change your avatar picture, it scared my kids.
P.P.S. I'll eventually use this thread as an example in a conference talk about trolling in open-source. You'll get your internet fame.

**Comment by eklipse2009** [comment]
Go fuck yourself yourself.
You took a lot of time to answer to me, but you could use a second to approve my commit, which would do no harm.
The "new project" is a wrapper on a wrapper to wrap class on a class. yo dawg. And besides it doesn't even connect to facebook and cannot get avatar from gravatar (although advertised).
I really wanted to be first to write "go fuck yourself", but you were first to turn it this way.

**Comment by panique** [comment]
I see that you have removed your ranting comment... This is so weak, so loser-style. Harassing others on the web for no reason and then removing it. Well done, dude.

I've already explained to you why this is not just pressing a button, excuse me please for not having the time to work for free for you. Don't you get this ? As said, people like you are why the world is a bad place: So much work and so much people say it's really useful for them, and then idiots like you come and make everything bad. If you don't like it, don't use it. If you don't understand that I don't have the time to maintain an officially dead 2-year-old project anymore, then nobody can help you. And as explained two times already, push to the forks!

I also don't discuss with subs like you why "the new script sucks". If you see a problem, try to fix it or write a proper ticket, don't bash around here for no particular reason.

"And besides it doesn't even connect to facebook and cannot get avatar from gravatar"

The project clearly explains why this feature was removed in favour of a new OAuth2 implementation (and a fast-developing FB API) in newer versions [he/she is talking about an other project, not this one]. Gravatars work fine like the live demo clearly shows. Also, even if features would break, then it's still not a reason to complain about this, as it's free software, written by unpaid volunteers.

It's very personal for me to fight against trolls like you, so this is why these answers are a little bit longer. People like you make the open-source scene a bad place. If I see you vandalizing or trolling around again, this will have consequences for you.

It's really weird that the most unsympathic, most stupid and most ugly people are always the ones that harass and troll for no logical reason.

**Comment by mikeq** [comment]
If you need a screenshot of the original comment for your conference talk let me know. I took one as I couldn't believe the ranting when you were nothing but nice.

**Pull request closed without merging**
